language: c

os:
  - linux
  - osx
  - windows

addons:
  homebrew:
    packages:
      - httpd
    update: true
  apt:
    packages:
      - apache2
      - apache2-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install apache-httpd --params '/installLocation:C:\' ; fi
  - cd mod_authnz_external

script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH="/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/:$PATH" ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cl mod_authnz_external.c -c -D_WINDOWS -IC:\\Apache24\\include ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then link /dll /libpath:C:\\Apache24\\lib libhttpd.lib libapr-1.lib libaprutil-1.lib mod_authnz_external.obj ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then sudo make install ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo service apache2 restart ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo brew services restart httpd ; fi