language: c

os:
  - linux
  - osx
  - windows

addons:
  homebrew:
    packages:
      - httpd
    update: true
  apt:
    packages:
      - apache2
      - apache2-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install apache-httpd --params '/installLocation:C:\Apache24' ; fi
  - cd mod_authnz_external

script:
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then make ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then nmake ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; sudo make install ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo service apache2 restart ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo brew services restart httpd ; fi